spring.application.name=springgraphql
spring.graphql.graphiql.enabled=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.com.jai=debug
logging.level.com.jai.springgraphql.controller.EmployeeController=DEBUG